default: &default
  host: localhost
  adapter: postgresql
  encoding: UTF8
  username: timbel
  timeout: 5000
  reaping_frequency: 30
  pool: 5

development:
  <<: *default
  database: development
  password: <%= Rails.application.secrets[:database][:password] %>

test:
  <<: *default
  database: test
  password: <%= Rails.application.secrets[:database][:password] %>

production:
  <<: *default
  database: production
  password: <%= ENV['EXERCISE_DATABASE_PASSWORD'] %>